Hurtownia/Models/Report.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Hurtownia.Models
{
    public class Report
    {

        public int ReportId { get; set; }



        [Required(ErrorMessage = "Name required-Cant be Blank")]
        public String question { get; set; }


        public String reply { get; set; }


        [DataType(DataType.Date)]
        public DateTime? DateOfCreation { get; set; }



        [DataType(DataType.Date)]
        public DateTime? DateOfAnwser { get; set; }

        //[Required(ErrorMessage = "Cant be null")]
        //public int reportIdentity { get; set; }

        //[Required(ErrorMessage = "Cant be null")]
        //public string message { get; set; }





        //[Required(ErrorMessage = "Cant be null")]
        //public string status { get;set; }

        public int UserId { get; set; }

        public virtual User user { get; set; }
    }
}

Hurtownia/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hurtownia.Models;
using Hurtownia.DAL;
using PagedList;
namespace Hurtownia.Controllers
{

    [Authorize(Roles = "Admin")]
    public class ReportController : Controller
    {
        private HurtowniaContext db = new HurtowniaContext();

        // GET: /Report/
        public ActionResult Index(int? page)
        {
            var reports = db.Reports.Include(r => r.user);
            reports = reports.OrderBy(s => s.DateOfCreation
);
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(reports.ToPagedList(pageNumber, pageSize));
           
        }

        // GET: /Report/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report report = db.Reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            return View(report);
        }

        // GET: /Report/Create
        public ActionResult Create(int id)
        {
            Report report = db.Reports.Find(id);
            report.DateOfAnwser = DateTime.Now;
            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName");
            return View(report);
        }

        // POST: /Report/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReportId,question,reply,DateOfCreation,UserId,DateOfAnwser")] Report report)
        {
            if (ModelState.IsValid)
            {
               
                db.Reports.Add(report);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName", report.UserId);
            return View(report);
        }

      

        // GET: /Report/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report report = db.Reports.Find(id);
            report.DateOfAnwser = DateTime.Now;
            if (report == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName", report.UserId);
            return View(report);
        }

        // POST: /Report/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReportId,question,reply,DateOfCreation,UserId,DateOfAnwser")] Report report)
        {
            if (ModelState.IsValid)
            {
                db.Entry(report).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.Users, "UserId", "UserName", report.UserId);
            return View(report);
        }

        // GET: /Report/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Report report = db.Reports.Find(id);
            if (report == null)
            {
                return HttpNotFound();
            }
            return View(report);
        }

        // POST: /Report/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Report report = db.Reports.Find(id);
            db.Reports.Remove(report);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hurtownia/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hurtownia.Models;
using Hurtownia.DAL;
using PagedList;
namespace Hurtownia.Controllers
{
   
    public class UserController : Controller
    {
        private HurtowniaContext db = new HurtowniaContext();

        // GET: /User/
        [Authorize(Roles="Admin")]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "DateOfCreation" : "Date";
            var users = from s in db.Users
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                users = users.Where(s => s.Name.Contains(searchString)
                                       || s.Surname.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name":
                    users = users.OrderByDescending(s => s.Name);
                    break;
                case "Surname":
                    users = users.OrderBy(s => s.Surname);
                    break;

                case "Date":
                    users = users.OrderBy(s => s.DateOfCreation);
                    break;


                case "DateOfCreation":
                    users = users.OrderByDescending(s => s.DateOfCreation);
                    break;

                default:
                    users = users.OrderBy(s => s.Name
);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(users.ToPagedList(pageNumber, pageSize));
        }


        // GET: /User/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: /User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="UserId,Name,Surname,DateOfCreation,Email")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: /User/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: /User/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="UserId,Name,Surname,DateOfCreation,Email")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: /User/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: /User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hurtownia/Views/Admin/Create.cshtml
@model Hurtownia.Models.Result

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Result</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, "ProductId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductId", String.Empty)
                @Html.ValidationMessageFor(model => model.ProductId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", String.Empty)
                @Html.ValidationMessageFor(model => model.UserId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductType)
                @Html.ValidationMessageFor(model => model.ProductType)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Hurtownia/Views/Admin/Delete.cshtml
@model Hurtownia.Models.Result

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Result</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductType)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Hurtownia/Views/Admin/Details.cshtml
@model Hurtownia.Models.Result

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Result</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductType)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Hurtownia/Views/Admin/Edit.cshtml
@model Hurtownia.Models.Statistic

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Result</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.ProductId, "ProductId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProductId", String.Empty)
                @Html.ValidationMessageFor(model => model.ProductId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", String.Empty)
                @Html.ValidationMessageFor(model => model.UserId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProductType)
                @Html.ValidationMessageFor(model => model.ProductType)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Hurtownia/Views/Admin/Index.cshtml
@model IEnumerable<Hurtownia.Models.Statistic>

@{
    ViewBag.Title = "Panel Admina";
}
<div class="page-header">




    <div class="list-group">
        <a href="#" class="list-group-item active">
            <h3>Admin Panel </h3> 
        </a>



        <ul class="list-group">
            <li class="list-group-item">      @Html.ActionLink("Category statistic", "CategoryCounter", "Home")  </li>
            <li class="list-group-item">       @Html.ActionLink("About Users", "About", "Home")  </li>
            <li class="list-group-item">         @Html.ActionLink("Users", "Index", "User")  </li>
            <li class="list-group-item">       @Html.ActionLink("Orders", "Index", "ControlOrders")  </li>
            <li class="list-group-item">    @Html.ActionLink("Order Statistic", "OrderCounter") </li>
            <li class="list-group-item">     @Html.ActionLink("Users Reports", "Index", "Report")  </li>
            <li class="list-group-item">       @Html.ActionLink("Users Address", "Shipping", "ControlOrders")</li>
           
        </ul>

    </div>



</div>

Hurtownia/Views/Admin/OrderCounterStatistics.cshtml
@model Hurtownia.ViewModels.Statystyki

@{
    ViewBag.Title = "Statystyki";
    var oc = ViewData["FeaturedProduct"] as Hurtownia.Models.OrderCounter;
}

<div class="page-header">
    <h1>OrderItems <small>Statistic</small></h1>
</div>

<div class="panel panel-primary">
    <!-- Default panel contents -->
    <div class="panel-heading">Table</div>
    <div class="panel-body">

        @if (ViewData["Popular"] != null)
        {

           
                    <table>

                        @foreach (Hurtownia.ViewModels.Statystyki statystyki in ViewData["Popular"] as List<Hurtownia.ViewModels.Statystyki>)
                        {
                            <tr>
                                <th>@statystyki.Nazwa</th>
                                <th> @statystyki.suma</th>
                                <th> Total  :@oc.Total(statystyki.Nazwa)</th>
                            </tr>
                        }
                    </table>
              

        }
  </div>
    @Html.ActionLink("Clear", "Clear", "Admin");
            </div>
            </div>

        </ul>

Hurtownia/Views/Admin/Reports.cshtml
@model IEnumerable<Hurtownia.Models.Report>

@{
    ViewBag.Title = "Reports";
}

<h2>Reports</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.user.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.user.UserName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.message)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ReportId }) |
            @Html.ActionLink("Details", "Details", new { id=item.ReportId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ReportId })
        </td>
    </tr>
}

</table>