Hurtownia/Hurtownia/Controllers/ControlOrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Hurtownia.Models;
using Hurtownia.DAL;
using PagedList;
namespace Hurtownia.Controllers
{
    public class ControlOrdersController : Controller
    {
        private HurtowniaContext db = new HurtowniaContext();

        // GET: /ControlOrders/
        public ActionResult Index(int ?page)
        {

            var customerOrders = db.CustomerOrders.Include(r => r.User);
            customerOrders = customerOrders.OrderBy(s => s.status
);
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(customerOrders.ToPagedList(pageNumber, pageSize));


        }

        public ActionResult Info(int? id)
        {



            var lista = db.OrderItems.Where(x => x.CustomerOrderId == id).OrderBy(x => x.Product.Name).ToList();




            return View(lista);
        }
        public ActionResult Shipping( string sortOrder,string currentFilter, string searchString, int? page)
        {
            var shipping = from s in db.Orders
                           select s;
            int id;
            int.TryParse(searchString, out id);

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name" : "";
           
            switch (sortOrder)
            {
                case "name_desc":
                    shipping = shipping.OrderByDescending(s => s.Name);
                    break;
            
               
                default:
                    shipping = shipping.OrderBy(s => s.Surname);
                    break;
            }
            if (searchString != null)
            {

                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                shipping = shipping.Where(s =>
               s.Name.ToUpper().Contains(searchString.ToUpper())
                ||
               s.Surname.ToUpper().Contains(searchString.ToUpper()) ||
               s.UserId == id);
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(shipping.ToPagedList(pageNumber, pageSize));
        }

        // GET: /ControlOrders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerOrder customerorder = db.CustomerOrders.Find(id);
            if (customerorder == null)
            {
                return HttpNotFound();
            }
            return View(customerorder);
        }

        // GET: /ControlOrders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /ControlOrders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="orderId,userId,status,totalCost")] CustomerOrder customerorder)
        {
            if (ModelState.IsValid)
            {
                db.CustomerOrders.Add(customerorder);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(customerorder);
        }

        // GET: /ControlOrders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerOrder customerorder = db.CustomerOrders.Find(id);
            if (customerorder == null)
            {
                return HttpNotFound();
            }
            return View(customerorder);
        }

        // POST: /ControlOrders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="orderId,userId,status,totalCost")] CustomerOrder customerorder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customerorder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customerorder);
        }

        // GET: /ControlOrders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CustomerOrder customerorder = db.CustomerOrders.Find(id);
            if (customerorder == null)
            {
                return HttpNotFound();
            }
            return View(customerorder);
        }

        // POST: /ControlOrders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CustomerOrder customerorder = db.CustomerOrders.Find(id);
            db.CustomerOrders.Remove(customerorder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hurtownia/Hurtownia/Views/ControlOrders/Create.cshtml
@model Hurtownia.Models.CustomerOrder

@{
    ViewBag.Title = "Create";
}
</br>
<div class="page-header">
    <h1>  Create <small>orders</small></h1>
</div>
</br>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
    
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.userId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userId)
                @Html.ValidationMessageFor(model => model.userId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status)
                @Html.ValidationMessageFor(model => model.status)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.totalCost, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.totalCost)
                @Html.ValidationMessageFor(model => model.totalCost)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hurtownia/Hurtownia/Views/ControlOrders/Delete.cshtml
@model Hurtownia.Models.CustomerOrder

@{
    ViewBag.Title = "Delete";
}

</br>
<div class="page-header">
    <h1>  Orders <small>delete</small></h1>
</div>
</br>

<h3>Are you sure you want to delete this?</h3>
<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.userId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.totalCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.totalCost)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Hurtownia/Hurtownia/Views/ControlOrders/Details.cshtml
@model Hurtownia.Models.CustomerOrder

@{
    ViewBag.Title = "Details";
}

</br>
<div class="page-header">
    <h1>  Orders <small>details</small></h1>
</div>
</br>
<div>
    
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.userId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.totalCost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.totalCost)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.orderId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Hurtownia/Hurtownia/Views/ControlOrders/Edit.cshtml
@model Hurtownia.Models.CustomerOrder

@{
    ViewBag.Title = "Edit";
}

</br>
<div class="page-header">
    <h1>  Orders <small>edit</small></h1>
</div>
</br>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
     
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.orderId)

        <div class="form-group">
            @Html.LabelFor(model => model.userId, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userId)
                @Html.ValidationMessageFor(model => model.userId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status)
                @Html.ValidationMessageFor(model => model.status)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.totalCost, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.totalCost)
                @Html.ValidationMessageFor(model => model.totalCost)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Hurtownia/Hurtownia/Views/ControlOrders/Index.cshtml
@model PagedList.IPagedList<Hurtownia.Models.CustomerOrder>
@using PagedList.Mvc;
@using PagedList;

</br>
<div class="page-header">
    <h1>  Orders <small>summary</small></h1>
</div>
</br>



<div class="panel panel-primary">
    <div class="panel-heading">Info</div>
    <div class="panel-body">
        <p></p>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>UserId</th>
                    <th>Name</th>
                    <th>Status</th>
                    <th>TotalCost</th>
                    <th>Options</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
             
                <tbody>
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.userId)</td>
                        <td>@Html.DisplayFor(modelItem => item.User.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.status)</td>
                        <td>@Html.DisplayFor(modelItem => item.totalCost)</td>
                     
                        <td>

                            @Html.ActionLink("Edit", "Edit", new { id = item.orderId }) |
                            @Html.ActionLink("Details", "Details", new { id = item.orderId }) |
                            @Html.ActionLink("Delete", "Delete", new { id = item.orderId }) |
                            @Html.ActionLink("Details of order", "Info", new { id = item.orderId })


                        </td>
                    </tr>
                </tbody>
            }
        </table>
    </div>
</div>

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

Hurtownia/Hurtownia/Views/ControlOrders/Info.cshtml
@model IEnumerable<Hurtownia.Models.Order>

@{
    ViewBag.Title = "Info";
}

</br>
<div class="page-header">
    <h1>  Customer <small>items</small></h1>
</div>
</br>


<div class="panel panel-primary">
    <div class="panel-heading">Info</div>
    <div class="panel-body">
        <p></p>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Quantity</th>
                    <th>Options</th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {

                <tbody>
                    <tr>
                        <td><img src="../../Images/@(item.Product.Image)" alt="" height="100px" width="100px" /></td>
                        <td>@Html.DisplayFor(modelItem => item.Product.Name)</td>
                        <td>@Html.DisplayFor(modelItem => item.quantity)</td>
                        @if (User.IsInRole("Admin"))
                        {


                            <td>
                                @Html.ActionLink("Delete", "Delete", new { id = item.itemId })
                            </td>
                        }
                    </tr>
                </tbody>
            }
        </table>
    </div>
</div>

Hurtownia/Hurtownia/Views/ControlOrders/Shipping.cshtml
@model PagedList.IPagedList<Hurtownia.Models.OrderShipping>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Shipping";
}

<div class="page-header">
    
    
    <div class="page-header">
        <h1>  Shipping <small>address</small></h1>
    </div>
    
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
    @using (Html.BeginForm("Shipping", "ControlOrders", FormMethod.Get))
    {
        <p>

            Find by name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as
string)
            <input type="submit" value="Search" />
        </p>
    }
</div>
    <table class="table">
        <tr>
            <th>
                UserId
            </th>
            <th>
                @Html.ActionLink("Name", "Shipping", new
        {
            sortOrder =
                ViewBag.NameSortParm
        })
            </th>
            <th>
                Surname
            </th>
            <th>
                Adres
            </th>
            <th>
                Adres1
            </th>
            <th>
                City
            </th>
            <th>
                ZipCode
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adres)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Adres1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ZipCode)
                </td>
                @*<td>
                        @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                        @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.Id })
                    </td>*@
            </tr>
        }

    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
    @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Shipping",
 new
 {
     page,
     sortOrder = ViewBag.CurrentSort,
     currentFilter =
         ViewBag.CurrentFilter
 }))